# Generated by Django 2.0.3 on 2020-06-02 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productadminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='客户姓名')),
                ('phone_number', models.CharField(max_length=12)),
                ('sale_price', models.FloatField(verbose_name='销售单价')),
                ('sale_number', models.IntegerField()),
                ('total_money', models.FloatField(verbose_name='合计金额')),
                ('pro_info', models.TextField(verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productadminapp.ProductAdmin')),
            ],
        ),
    ]
