# Generated by Django 2.0.3 on 2020-06-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_code', models.IntegerField()),
                ('pro_type', models.CharField(max_length=100)),
                ('pro_price', models.FloatField(verbose_name='商品价格')),
                ('pro_kuwei', models.IntegerField()),
                ('pro_intro', models.TextField(verbose_name='产品备注')),
                ('usertable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.UserTable')),
            ],
        ),
    ]
